name: CI
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git checkout main
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: install-buf
        run: |
          chmod +x install-buf.sh
          ./install-buf.sh
      - name: buf lint && buf breaking
        run: |
          buf lint
          buf breaking --against '.git#branch=main'