name: generator
on:
  release:
    types: [created]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git checkout main
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Install requirements
        run: |
          chmod +x install-requirements.sh
          ./install-requirements.sh
      - name: buf lint
        run: |
          buf lint
          buf breaking --against '.git#branch=main'
  generate-go:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Install requirements
        run: |
          chmod +x install-requirements.sh
          ./install-requirements.sh
      - name: buf generate
        run: buf generate
      - name: Prepare Go repo
        run: |
          chmod +x prepare-repository.sh
          ./prepare-repository.sh "https://github.com/CowNetwork/mooapis-go.git" "./gen/go" "./out"
          cd ./out/
          git diff-index --quiet HEAD || git commit -m "Generate Go files for $RELEASE_VERSION"
          git tag $RELEASE_VERSION
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.UDDER_MACHINE_ACCESS_TOKEN }}
          branch: main
          directory: ./mooapis-go
          repository: cownetwork/mooapis-go
          tags: true
  generate-java:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Install requirements
        run: |
          chmod +x install-requirements.sh
          ./install-requirements.sh
      - name: buf generate
        run: buf generate
      - name: Apply Java template
        run: |
          chmod +x apply-java-template.sh
          ./apply-java-template.sh "./gen/java" "./template/java/" "./gen/java"
      - name: Prepare Java repo
        run: |
          chmod +x prepare-repository.sh
          ./prepare-repository.sh "https://github.com/CowNetwork/mooapis-java.git" "./gen/java" "./out"
          cd ./out/
          git diff-index --quiet HEAD || git commit -m "Generate Java files for $RELEASE_VERSION"
          git tag $RELEASE_VERSION
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.UDDER_MACHINE_ACCESS_TOKEN  }}
          branch: main
          directory: ./mooapis-java
          repository: cownetwork/mooapis-java
          tags: true
